/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelma;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Shubham Goyal
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        mb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ac = new javax.swing.JRadioButton();
        nac = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        se = new javax.swing.JRadioButton();
        de = new javax.swing.JRadioButton();
        te = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        datein = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        dateout = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        nrooms = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        advmoney = new javax.swing.JTextField();
        rno = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 58, 16);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(290, 60, 102, 22);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 160, 70, 16);

        add.setColumns(20);
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 150, 166, 96);

        jLabel3.setText("Mobile no.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 350, 90, 16);

        mb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbActionPerformed(evt);
            }
        });
        getContentPane().add(mb);
        mb.setBounds(280, 360, 137, 22);

        jLabel4.setText("Check in date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 430, 80, 16);

        jLabel5.setText("Room type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 550, 80, 16);

        ac.setText("Ac");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(120, 580, 43, 25);

        nac.setText("Non-Ac");
        nac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacActionPerformed(evt);
            }
        });
        getContentPane().add(nac);
        nac.setBounds(270, 580, 107, 25);

        jLabel6.setText("No of bed");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 620, 90, 16);

        se.setText("single");
        getContentPane().add(se);
        se.setBounds(70, 650, 61, 25);

        de.setText("double");
        getContentPane().add(de);
        de.setBounds(200, 650, 67, 25);

        te.setText("tripple");
        te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teActionPerformed(evt);
            }
        });
        getContentPane().add(te);
        te.setBounds(330, 650, 65, 25);

        jLabel7.setText("Customer id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 770, 90, 16);

        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        getContentPane().add(cid);
        cid.setBounds(270, 760, 100, 22);

        jLabel9.setText("State");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 290, 50, 16);
        getContentPane().add(st);
        st.setBounds(240, 290, 180, 22);
        getContentPane().add(datein);
        datein.setBounds(190, 430, 100, 22);

        jLabel10.setText("Checkout Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 430, 90, 16);
        getContentPane().add(dateout);
        dateout.setBounds(570, 430, 100, 22);

        jLabel11.setText("No of Rooms");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 490, 80, 20);
        getContentPane().add(nrooms);
        nrooms.setBounds(200, 490, 130, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelma/update.png"))); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 790, 79, 25);

        jLabel8.setText("Room no");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 720, 70, 16);

        jLabel12.setText("Advance money");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 810, 90, 16);
        getContentPane().add(advmoney);
        advmoney.setBounds(260, 810, 110, 22);

        getContentPane().add(rno);
        rno.setBounds(260, 720, 100, 22);

        jButton2.setText("See rooms");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 670, 120, 25);

        jMenuBar1.setForeground(new java.awt.Color(0, 204, 153));
        jMenuBar1.setToolTipText("");

        jMenu1.setText("Room Details");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu9.setText("New Booking");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu2.setText("Cancel Booking");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Update");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void mbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbActionPerformed

    private void nacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacActionPerformed

    private void teActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
        Frame2 f=new Frame2();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bname=name.getText().trim();
        String badd=add.getText().trim();
        String bst=st.getText().trim();
        String bmb=mb.getText().trim();
         String bdatein=DateFormat.getDateInstance().format(datein.getDate());
        //String bdateout=dateout.getName().trim();
        String bdateout=DateFormat.getDateInstance().format(dateout.getDate());
        int nrm=Integer.parseInt(nrooms.getText().trim());
        String broomtype,broombed;
        if(ac.isSelected())
            broomtype="ac";
        else
            broomtype="nonac";
                    if(se.isSelected())
                    {
                        broombed="single";
                    }
                    else if(de.isSelected())
                    {
                        broombed="double";
                    }
                    else
                        broombed="triple";
                    int rm=Integer.parseInt(rno.getSelectedItem().toString());
                    String id=cid.getText();
                    int adv=Integer.parseInt(advmoney.getText().trim());
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/projectjava","root","shubham");
                PreparedStatement s=c.prepareStatement("insert into roomtable values(?,?,?,?,?,?,?,?,?,?,?,?)");
                s.setInt(1,rm);
                s.setString(2,"true");
                s.setString(3,id);
                s.setString(4,bdatein);
                        s.setString(5,bdateout);
                        s.setString(6,bmb);
                        s.setString(7,bname);
                        s.setString(8,broomtype);
                        s.setString(9,broombed);
                        s.setInt(10,adv);
                        s.setString(11,badd);
                        s.setString(12,bst);
                        
                        int re=s.executeUpdate();
                        if(re>0)
                        {
                            javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to book another","Booking window",JOptionPane.YES_NO_CANCEL_OPTION);
                            Connection c1=DriverManager.getConnection("jdbc:mysql://localhost:3306/projectjava","root","shubham");
                            PreparedStatement s1=c1.prepareStatement("update checktable set empty=? where Roomid=?");
                            s1.setString(1,"false");
                            s1.setInt(2,rm);
                            s1.executeUpdate();
                        }
                        else
                        {
                            javax.swing.JOptionPane.showMessageDialog(this,"try again");
                        }
            }
            catch(Exception e)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Contact admin"+e);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String broomtype,broombed;
         String temp="true";
        if(ac.isSelected())
            broomtype="ac";
        else
            broomtype="nonac";
                    if(se.isSelected())
                    {
                        broombed="single";
                    }
                    else if(de.isSelected())
                    {
                        broombed="double";
                    }
                    else
                        broombed="triple";
                   try{ 
                     Class.forName("com.mysql.jdbc.Driver");
            Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/projectjava","root","shubham");
            //Statement s=c.createStatement();
            //ResultSet r=s.executeQuery("select * from mainframetable where Typ")
            PreparedStatement s=c.prepareStatement("select * from checktable where Type=? and Bed=? and empty=?");
            s.setString(1,broomtype);
            s.setString(2,broombed);
            s.setString(3,temp);
            ResultSet r=s.executeQuery();
            while(r.next())
            {
                rno.addItem(r.getString(1));
            }
                   }
                   catch(Exception e)
                   {
                       javax.swing.JOptionPane.showMessageDialog(this,"contact admin"+e);
                   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Frame1 f=new Frame1();
           f.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:4
        Frame3 f=new Frame3();
           f.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Frame4 f=new Frame4();
           f.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        Frame5 f=new Frame5();
           f.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ac;
    private javax.swing.JTextArea add;
    private javax.swing.JTextField advmoney;
    private javax.swing.JTextField cid;
    private com.toedter.calendar.JDateChooser datein;
    private com.toedter.calendar.JDateChooser dateout;
    private javax.swing.JRadioButton de;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mb;
    private javax.swing.JRadioButton nac;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nrooms;
    private javax.swing.JComboBox<String> rno;
    private javax.swing.JRadioButton se;
    private javax.swing.JTextField st;
    private javax.swing.JRadioButton te;
    // End of variables declaration//GEN-END:variables
}
