/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelma;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Shubham Goyal
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        umob = new javax.swing.JTextField();
        upasswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));
        setPreferredSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shubham Goyal\\Desktop\\Computer\\hotel-management-system.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 280, 180);

        jLabel2.setText("Enter username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 361, 110, 16);
        getContentPane().add(uname);
        uname.setBounds(277, 355, 120, 22);

        jLabel3.setText("Enter password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 430, 100, 16);

        jButton1.setText("Create account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 570, 130, 25);

        jLabel4.setText("Enter mobile no.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 520, 110, 16);
        getContentPane().add(umob);
        umob.setBounds(270, 510, 140, 22);
        getContentPane().add(upasswd);
        upasswd.setBounds(270, 430, 140, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String a=uname.getText().trim();
            String b=new String(upasswd.getPassword());
            String m=umob.getText().trim();
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/projectjava","root","shubham");
            PreparedStatement s=c.prepareStatement("insert into customerlogin values(?,?,?)");
            s.setString(1,a);
            s.setString(2,b);
            s.setString(3,m);
            int re=s.executeUpdate();
            if(re>0)
            {
                javax.swing.JOptionPane.showMessageDialog(this,"Successful");
                 MainFrame p=new MainFrame();
                p.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,"Not successful");
            }
            
        }
        catch(Exception e)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "contact admin"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField umob;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upasswd;
    // End of variables declaration//GEN-END:variables
}
